export const ERROR_CODES = {
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    PHONE_PE_CALL_FAILED: "PHONE_PE_CALL_FAILED",
    AMOUNT_FIELD_IS_REQUIRED: "AMOUNT_FIELD_IS_REQUIRED",
    ENTER_VALID_AMOUNT: "ENTER_VALID_AMOUNT",
    RECEIVER_UPI_ID_FIELD_IS_MISSING: "RECEIVER_UPI_ID_FIELD_IS_MISSING",
    ENTER_VALID_RECEIVER_UPI_ID: "ENTER_VALID_RECEIVER_UPI_ID",
    ENTER_VALID_NOTE: "ENTER_VALID_NOTE",
    REQUEST_BODY_HAS_EXTRA_FIELDS: "REQUEST_BODY_HAS_EXTRA_FIELDS",
    REQUEST_BODY_IS_REQUIRED: "REQUEST_BODY_IS_REQUIRED",
}